# { {- if .Values.rbac.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: hpcc
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: hpcc
rules:
  - apiGroups:
      - "batch"
    resources:
      - jobs
    verbs:
      - get
      - create
      - list
      - delete
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: hpcc
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: hpcc
subjects:
  - kind: ServiceAccount
    name: hpcc
    #namespace: hpcc
#{ {- end -}}
